Add solution to "Foregone Solution" problem
To be investigated on why  works only locally, on competition interface I get a compilation error:
Solution.ts(2,27): error TS2307: Cannot find module 'readline'.
Solution.ts(5,10): error TS2304: Cannot find name 'process'.
Solution.ts(6,11): error TS2304: Cannot find name 'process'.
Solution.ts(23,36): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.