Fix "Cannot find name process or module readline"
GCJ online compiler was failing with the following errors:
Solution.ts(1,18): error TS2304: Cannot find name 'require'.
Solution.ts(4,10): error TS2304: Cannot find name 'process'.
Solution.ts(5,11): error TS2304: Cannot find name 'process'.